- name: Personal accounts
  ansible.builtin.include_tasks: users.yml
  tags: [login, users]

- name: Sudo
  ansible.builtin.include_tasks: sudo.yml
  tags: [login, sudo]

- name: SSH hardening
  ansible.builtin.include_tasks: ssh.yml
  tags: [login, ssh]
